In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
# Load the dataset
df_counts = pd.read_csv('species_frequency_counts.csv')
df_counts.head()

                   Species  Frequency
0  Troglodytes troglodytes     334516
1       Erithacus rubecula     330418
2        Turdus philomelos     231606
3            Turdus merula     201057
4      Cyanistes caeruleus     127129

In [14]:
df_conv = pd.read_csv('common_sci.csv')
df_conv = df_conv[['PRIMARY_COM_NAME','SCI_NAME']]
df_conv.head()

        PRIMARY_COM_NAME                        SCI_NAME
0         Common Ostrich                Struthio camelus
1         Somali Ostrich          Struthio molybdophanes
2  Common/Somali Ostrich  Struthio camelus/molybdophanes
3     Southern Cassowary             Casuarius casuarius
4        Dwarf Cassowary              Casuarius bennetti

In [21]:
df_conv_freq = df_counts.merge(df_conv, left_on='Species', right_on='SCI_NAME', how='left').drop(columns=['SCI_NAME'])
df_conv_freq.head(12)

                    Species  Frequency      PRIMARY_COM_NAME
0   Troglodytes troglodytes     334516         Eurasian Wren
1        Erithacus rubecula     330418        European Robin
2         Turdus philomelos     231606           Song Thrush
3             Turdus merula     201057    Eurasian Blackbird
4       Cyanistes caeruleus     127129     Eurasian Blue Tit
5        Sylvia atricapilla     121863     Eurasian Blackcap
6    Phylloscopus collybita     105590     Common Chiffchaff
7            Sitta europaea      62812     Eurasian Nuthatch
8        Certhia familiaris      59572  Eurasian Treecreeper
9               Strix aluco      52858             Tawny Owl
10           Periparus ater      42343              Coal Tit
11              Parus major      40520             Great Tit

In [34]:
df_conv_freq.head(12)

                    Species  Frequency      PRIMARY_COM_NAME
0   Troglodytes troglodytes     334516         Eurasian Wren
1        Erithacus rubecula     330418        European Robin
2         Turdus philomelos     231606           Song Thrush
3             Turdus merula     201057    Eurasian Blackbird
4       Cyanistes caeruleus     127129     Eurasian Blue Tit
5        Sylvia atricapilla     121863     Eurasian Blackcap
6    Phylloscopus collybita     105590     Common Chiffchaff
7            Sitta europaea      62812     Eurasian Nuthatch
8        Certhia familiaris      59572  Eurasian Treecreeper
9               Strix aluco      52858             Tawny Owl
10           Periparus ater      42343              Coal Tit
11              Parus major      40520             Great Tit

In [ ]:
# count records with no PRIMARY_COM_NAME
missing_count = df_conv_freq['PRIMARY_COM_NAME'].isna().sum()
print(missing_count)

195

In [38]:
unconv = df_conv_freq[df_conv_freq['PRIMARY_COM_NAME'].isna()]
print("Unconverted species:")
unconv.head()

Unconverted species:

                            Species  Frequency PRIMARY_COM_NAME
20        Pholidoptera griseoaptera      17039              NaN
63              Capreolus capreolus       2691              NaN
64                    Vulpes vulpes       2676              NaN
78              Anaxyrus americanus       1701              NaN
82  Domestic_sounds_and_home_sounds       1564              NaN

In [25]:
nilo_freq = [1646370, 1592189, 929896, 829954, 460416, 399303, 327395, 138739, 129551, 121672]
nilo_spec = ['Eurasian Wren', 'European Robin', 'Song Thrush', 'Eurasian Blackbird', 'Common Chiffchaff', 'Eurasian Blue Tit', 'Eurasian Blackcap', 'Coal Tit', 'Tawny Owl', 'Eurasian Nuthatch']

In [26]:
df_nilo = pd.DataFrame({'Species': nilo_spec, 'Frequency': nilo_freq})
df_nilo.head()

              Species  Frequency
0       Eurasian Wren    1646370
1      European Robin    1592189
2         Song Thrush     929896
3  Eurasian Blackbird     829954
4   Common Chiffchaff     460416

In [32]:
df_compare = df_conv_freq.merge(df_nilo, left_on='PRIMARY_COM_NAME', right_on='Species', how='left')
df_compare['ratio'] = df_compare['Frequency_y'] / df_compare['Frequency_x']
df_compare.head(15)

,Species_x,Frequency_x,PRIMARY_COM_NAME,Species_y,Frequency_y,ratio
0,Troglodytes troglodytes,334516,Eurasian Wren,Eurasian Wren,1646370.0,4.921648
1,Erithacus rubecula,330418,European Robin,European Robin,1592189.0,4.818711
2,Turdus philomelos,231606,Song Thrush,Song Thrush,929896.0,4.014991
3,Turdus merula,201057,Eurasian Blackbird,Eurasian Blackbird,829954.0,4.127954
4,Cyanistes caeruleus,127129,Eurasian Blue Tit,Eurasian Blue Tit,399303.0,3.140928
5,Sylvia atricapilla,121863,Eurasian Blackcap,Eurasian Blackcap,327395.0,2.686582
6,Phylloscopus collybita,105590,Common Chiffchaff,Common Chiffchaff,460416.0,4.360413
7,Sitta europaea,62812,Eurasian Nuthatch,Eurasian Nuthatch,121672.0,1.937082
8,Certhia familiaris,59572,Eurasian Treecreeper,NaN,NaN,NaN
9,Strix aluco,52858,Tawny Owl,Tawny Owl,129551.0,2.450925
10,Periparus ater,42343,Coal Tit,Coal Tit,138739.0,3.276551
11,Parus major,40520,Great Tit,NaN,NaN,NaN
12,Regulus regulus,34039,Goldcrest,NaN,NaN,NaN
13,Fringilla coelebs,33930,Common Chaffinch,NaN,NaN,NaN
14,Dendrocopos major,32719,Great Spotted Woodpecker,NaN,NaN,NaN

In [45]:
df_conv_freq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   scientificName  994 non-null    object
 1   Frequency       994 non-null    int64
 2   Common Name     799 non-null    object
dtypes: int64(1), object(2)
memory usage: 23.4+ KB

In [39]:
df_conv_freq.rename(columns={'PRIMARY_COM_NAME': 'Common Name', 'Species': 'scientificName'}, inplace=True)

In [40]:
df_conv_freq.head()

            scientificName  Frequency         Common Name
0  Troglodytes troglodytes     334516       Eurasian Wren
1       Erithacus rubecula     330418      European Robin
2        Turdus philomelos     231606         Song Thrush
3            Turdus merula     201057  Eurasian Blackbird
4      Cyanistes caeruleus     127129   Eurasian Blue Tit

In [41]:
df_conv_freq.to_csv('converted_species.csv', index=False)

In [50]:
df_conv_freq[df_conv_freq['Common Name'].isna()].head(10)

                      scientificName  Frequency Common Name
20         Pholidoptera griseoaptera      17039         NaN
63               Capreolus capreolus       2691         NaN
64                     Vulpes vulpes       2676         NaN
78               Anaxyrus americanus       1701         NaN
82   Domestic_sounds_and_home_sounds       1564         NaN
83             Lithobates sylvaticus       1555         NaN
88               Pseudacris crucifer       1376         NaN
92           Tettigettalna argentata       1298         NaN
131             Water_tap_and_faucet        502         NaN
141             Cystosoma saundersii        426         NaN